name: Build and deploy to ECS
on: 
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu:latest
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
        #clone repository into the runner
            - name: clone repo
              uses: actions/checkout@v4
        #intsall maven and java
            - name: setup java and maven
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '11'
        #to create artifact with maven
            - name: package-artifact
              run: mvn package-artifact
        #to run code analysis with sonarqube
            - name: code analysis with sonarqube
              run: mvn sonar:sonar -Dsonar.projectKey=drix-webapp-project -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.token=${{secrets.SONAR_LOGIN_TOKEN}}
        #PUBLISH to github packages
            - name: publish togithub packages
              run: mvn --batch-mode deploy
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
